name: peru_poverty_sat
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.10
  - pip
  - pip:
      - -e .
  - pyreadstat
  - autopep8
  - pyarrow
  - numpy
  - scikit-learn
  - jupyter
